// 函数名称: sub_406020
// 虚拟地址: 0x406020
// 源二进制: E:/torrent/Cursor/Race/steamapps/common/Race for the Galaxy/Race.exe.bndb

void __convention("regparm")sub_406020(float* arg1, float* arg2, float* arg3)
{
    // 第一条实际指令: long double x87_r7_3 = fconvert.t(*arg2) * fconvert.t(*arg3) + fconvert.t(arg2[1]) * fconvert.t(arg3[4]) + fconvert.t(arg3[8]) * fconvert.t(arg2[2]) + fconvert.t(arg3[0xc]) * fconvert.t(arg2[3])
    long double x87_r7_3 = fconvert.t(*arg2) * fconvert.t(*arg3)
        + fconvert.t(arg2[1]) * fconvert.t(arg3[4]) + fconvert.t(arg3[8]) * fconvert.t(arg2[2])
        + fconvert.t(arg3[0xc]) * fconvert.t(arg2[3])
    *arg1 = fconvert.s(x87_r7_3)
    arg1[1] = fconvert.s(fconvert.t(arg3[5]) * fconvert.t(arg2[1])
        + fconvert.t(arg3[1]) * fconvert.t(*arg2) + fconvert.t(arg2[2]) * fconvert.t(arg3[9])
        + fconvert.t(arg3[0xd]) * fconvert.t(arg2[3]))
    arg1[2] = fconvert.s(fconvert.t(arg3[6]) * fconvert.t(arg2[1])
        + fconvert.t(arg3[2]) * fconvert.t(*arg2) + fconvert.t(arg2[2]) * fconvert.t(arg3[0xa])
        + fconvert.t(arg2[3]) * fconvert.t(arg3[0xe]))
    arg1[3] = fconvert.s(fconvert.t(arg3[7]) * fconvert.t(arg2[1])
        + fconvert.t(arg3[3]) * fconvert.t(*arg2) + fconvert.t(arg2[2]) * fconvert.t(arg3[0xb])
        + fconvert.t(arg3[0xf]) * fconvert.t(arg2[3]))
    arg1[4] = fconvert.s(fconvert.t(arg2[5]) * fconvert.t(arg3[4])
        + fconvert.t(arg2[4]) * fconvert.t(*arg3) + fconvert.t(arg3[8]) * fconvert.t(arg2[6])
        + fconvert.t(arg3[0xc]) * fconvert.t(arg2[7]))
    arg1[5] = fconvert.s(fconvert.t(arg3[5]) * fconvert.t(arg2[5])
        + fconvert.t(arg2[4]) * fconvert.t(arg3[1]) + fconvert.t(arg2[6]) * fconvert.t(arg3[9])
        + fconvert.t(arg3[0xd]) * fconvert.t(arg2[7]))
    arg1[6] = fconvert.s(fconvert.t(arg2[5]) * fconvert.t(arg3[6])
        + fconvert.t(arg2[4]) * fconvert.t(arg3[2]) + fconvert.t(arg2[6]) * fconvert.t(arg3[0xa])
        + fconvert.t(arg3[0xe]) * fconvert.t(arg2[7]))
    arg1[7] = fconvert.s(fconvert.t(arg3[7]) * fconvert.t(arg2[5])
        + fconvert.t(arg2[4]) * fconvert.t(arg3[3]) + fconvert.t(arg2[6]) * fconvert.t(arg3[0xb])
        + fconvert.t(arg3[0xf]) * fconvert.t(arg2[7]))
    arg1[8] = fconvert.s(fconvert.t(arg2[9]) * fconvert.t(arg3[4])
        + fconvert.t(arg2[8]) * fconvert.t(*arg3) + fconvert.t(arg3[8]) * fconvert.t(arg2[0xa])
        + fconvert.t(arg3[0xc]) * fconvert.t(arg2[0xb]))
    arg1[9] = fconvert.s(fconvert.t(arg3[5]) * fconvert.t(arg2[9])
        + fconvert.t(arg2[8]) * fconvert.t(arg3[1]) + fconvert.t(arg2[0xa]) * fconvert.t(arg3[9])
        + fconvert.t(arg3[0xd]) * fconvert.t(arg2[0xb]))
    arg1[0xa] = fconvert.s(fconvert.t(arg2[9]) * fconvert.t(arg3[6])
        + fconvert.t(arg2[8]) * fconvert.t(arg3[2]) + fconvert.t(arg2[0xa]) * fconvert.t(arg3[0xa])
        + fconvert.t(arg2[0xb]) * fconvert.t(arg3[0xe]))
    arg1[0xb] = fconvert.s(fconvert.t(arg3[7]) * fconvert.t(arg2[9])
        + fconvert.t(arg2[8]) * fconvert.t(arg3[3]) + fconvert.t(arg2[0xa]) * fconvert.t(arg3[0xb])
        + fconvert.t(arg3[0xf]) * fconvert.t(arg2[0xb]))
    arg1[0xc] = fconvert.s(fconvert.t(arg2[0xc]) * fconvert.t(*arg3)
        + fconvert.t(arg2[0xd]) * fconvert.t(arg3[4]) + fconvert.t(arg3[8]) * fconvert.t(arg2[0xe])
        + fconvert.t(arg2[0xf]) * fconvert.t(arg3[0xc]))
    arg1[0xd] = fconvert.s(fconvert.t(arg3[5]) * fconvert.t(arg2[0xd])
        + fconvert.t(arg2[0xc]) * fconvert.t(arg3[1]) + fconvert.t(arg2[0xe]) * fconvert.t(arg3[9])
        + fconvert.t(arg2[0xf]) * fconvert.t(arg3[0xd]))
    arg1[0xe] = fconvert.s(fconvert.t(arg2[0xd]) * fconvert.t(arg3[6])
        + fconvert.t(arg3[2]) * fconvert.t(arg2[0xc]) + fconvert.t(arg3[0xa]) * fconvert.t(arg2[0xe])
        + fconvert.t(arg2[0xf]) * fconvert.t(arg3[0xe]))
    arg1[0xf] = fconvert.s(fconvert.t(arg3[7]) * fconvert.t(arg2[0xd])
        + fconvert.t(arg2[0xc]) * fconvert.t(arg3[3]) + fconvert.t(arg2[0xe]) * fconvert.t(arg3[0xb])
        + fconvert.t(arg2[0xf]) * fconvert.t(arg3[0xf]))
}
